In [1]:
# 8 패키지와 라이브러리
# 8-3 내장함수
# 내장함수 예 : input
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 안뇽
안뇽


In [2]:
#9 NumPy
#9-1 List를 사용한 다차원 배열
# List를 이용한 다차원 배열
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]  #실수 list를 생성

In [3]:
# flVal 3개를 리스트로 구성하여 arVal 다차원 배열을 생성
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [4]:
# arVal은 다차원 배열이므로, arVal[n] 인덱스 연산을 통해 n차원 배열 값을 출력
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [5]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1][2]

3.14

In [7]:
# 1 차원 값을 변환하여 다른 값을 대입 했을때의 다차원 배열
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [8]:
arVal[0][2]

't'

In [9]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [10]:
# 9-2 NumPy 배열
# numpy 패치지를 import 
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [11]:
# 다양한 NumPy 배열 함수들
# 배열 각 요소의 합을 출력
arData.sum()

15.44

In [12]:
arVal.sum()

AttributeError: ignored

In [13]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
# 배열에 대한 표준편차 출력
arData.std()

1.4717934637713266

In [15]:
# 배열의 누적 합을 출력
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [16]:
# 벡터화된 NumPy 배열 수학 연산 지원
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [17]:
arData ** 2 #2제곱

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [18]:
# 루트를 적용한 값을 출력
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [19]:
# axis 축을 기준으로 합계 표현
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [20]:
arVal.sum(axis=0) # 축(axis)이 0일 경우 세로 축의 합을 출력

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [21]:
arVal.sum(axis=1) # 축(axis)이 0일 경우 가로 축의 합을 출력

array([15.44  , 58.5096])

In [22]:
# NumPy.array를 사용한 코드
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
# NumPy.zeros를 사용한 코드
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [24]:
# 10 Pandas
# 10-1 Series
# pandas import
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [25]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [26]:
pandas_series[0]

30

In [27]:
pandas_series[0][1]

IndexError: ignored

In [28]:
# 10-2 DataFrame
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [29]:
# DataFrame의 index를 표시
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [30]:
# DataFrame의 column을 표시
df.columns

Index(['score'], dtype='object')

In [31]:
# DataFrame의index 중에서 국어에 해당하는 값을 출력
df.loc['국어']   # ix 함수가 최근 제거되어 loc를 써야 동작

score    30
Name: 국어, dtype: int64

In [32]:
# DataFrame의 값을 모두 합한 결과를 출력
df.sum()

score    60
dtype: int64

In [33]:
# DataFrame의 각 colimn 값의 제곱을 출력
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [34]:
# DataFrame에 score2 라는 칼럼을 추가하고 값을 입력
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [35]:
# DataFrame 함수를 이용하여 column을 추가할 수 있음
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [36]:
# column 삭제
del df['score']

In [37]:
# index 를 맞추기 않았을 경우
df['score2'] = (90, 90, 90, 100)

ValueError: ignored

In [38]:
# index 를 맞추기 않았을 경우
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [39]:
# join() 함수를 이용하여 2개의 DataFrame을 하나로 합칠 수 있음
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [40]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [41]:
# 난수를 이용한 임의의 값 생성
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']
df

A         B         C         D         E
0 -0.760446  0.034851 -1.584002 -0.324525 -0.958386
1  0.421443  0.777467  0.606821  0.514329  0.121103
2  0.604298 -1.269707  2.108500 -0.531646 -1.017463
3 -0.202849  1.189337  1.515339 -0.485211  0.708993
4 -0.551734  0.044521  0.826603  1.149957 -0.078964

In [42]:
# 최대값
df.max()

A    0.604298
B    1.189337
C    2.108500
D    1.149957
E    0.708993
dtype: float64

In [43]:
# 최소값
df.min()

A   -0.760446
B   -1.269707
C   -1.584002
D   -0.531646
E   -1.017463
dtype: float64

In [44]:
# 평균
df.mean()

A   -0.097858
B    0.155294
C    0.694652
D    0.064581
E   -0.244943
dtype: float64

In [45]:
# 표준편차
df.std()

A    0.595556
B    0.937250
C    1.404447
D    0.739844
E    0.737787
dtype: float64

In [46]:
# 누적값
df.cumsum()

A         B         C         D         E
0 -0.760446  0.034851 -1.584002 -0.324525 -0.958386
1 -0.339003  0.812318 -0.977180  0.189804 -0.837283
2  0.265295 -0.457389  1.131320 -0.341842 -1.854746
3  0.062446  0.731947  2.646659 -0.827053 -1.145753
4 -0.489288  0.776468  3.473261  0.322904 -1.224717

In [47]:
# DataFrame의 통계적 요약
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -0.097858  0.155294  0.694652  0.064581 -0.244943
std    0.595556  0.937250  1.404447  0.739844  0.737787
min   -0.760446 -1.269707 -1.584002 -0.531646 -1.017463
25%   -0.551734  0.034851  0.606821 -0.485211 -0.958386
50%   -0.202849  0.044521  0.826603 -0.324525 -0.078964
75%    0.421443  0.777467  1.515339  0.514329  0.121103
max    0.604298  1.189337  2.108500  1.149957  0.708993

In [48]:
# Group by를 이용한 DataFrame의 그룹화
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0 -0.760446  0.034851 -1.584002 -0.324525 -0.958386        X
1  0.421443  0.777467  0.606821  0.514329  0.121103        Y
2  0.604298 -1.269707  2.108500 -0.531646 -1.017463        X
3 -0.202849  1.189337  1.515339 -0.485211  0.708993        Y
4 -0.551734  0.044521  0.826603  1.149957 -0.078964        Z

In [49]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X        -0.078074 -0.617428  0.262249 -0.428085 -0.987924
Y         0.109297  0.983402  1.061080  0.014559  0.415048
Z        -0.551734  0.044521  0.826603  1.149957 -0.078964